### ISSUE TITLE
onSuccess works unexpectedly when there is multiple hooks with the same key.

### ISSUE THREAD

**Issue by andykao1213** [vercel/swr#1125]
# Bug report

Firstly, I want to thank for your hard work on swr. It is an amazing library which helps me a lot of my every day work!

## Description / Observed Behavior

I am trying to use the same key in different hooks as follow:
```jsx
function ChildComp() {
  useSWR("key", fetcher);
  // ...
}

function ParentComp() {
  useSWR("key", fetcher, { onSuccess: () => console.log("Parent success") });

  return (
    <div>
      <ChildComp />
     // ....
    </div>
  );
}
```
The callback `onSuccess` wasn't triggered. But I found that if I put a callback in the hook in `ChildComp`. The callback in the child fired but not the one in the parent.

## Expected Behavior

All of the `onSuccess` callback should be triggered

## Repro Steps / Code Example

Here is a [CSB](https://codesandbox.io/s/onsuccess-issue-in-swr-5zku0?file=/src/App.js). Just open the console to see the behavior

## Additional Context

SWR version. 
0.5.4

**Comment by promer94** [comment]
Thanks for you repro !

This is expected behavior.  SWR will deduped the requests with the same key in a short period by default (2000ms) 

1. Child Component mounted and fetcher fired, then call the onSuccess callback
2. Parent Component will reuse the request created by child component. The fetcher in parent will not fire, so the onSuccess won't be called.

FYI: https://codesandbox.io/s/onsuccess-issue-in-swr-forked-9337f?file=/src/App.js

**Comment by andykao1213** [comment]
@promer94 Thanks for the reply. I misunterstook the mechanism of `onSuccess`. It now make sense to me. I'll close the issue. Thank you!
