### ISSUE TITLE
Removing cookie in example triggers infinite redirect loop

### ISSUE THREAD

**Issue by mikefrancis** [vercel/swr#1147]
# Bug report

On the CodeSandbox for the [authentication example](https://swr.vercel.app/examples/auth), when removing the cookie (or changing the value) in DevTools to simulate being logged out by expiry, and then refocussing the window, the app goes into a redirect loop.

I'm not sure if this is a bug with SWR or the example, but I'm having the same problem with my app so would be great to get to the bottom of it.

## Description / Observed Behavior

The app goes into a redirect loop.

## Expected Behavior

The user would be redirected to the login page.

## Repro Steps / Code Example

[CodeSandbox](https://codesandbox.io/s/swr-auth-tuqtf)

## Additional Context

SWR version: 

- 0.3.0-beta.3 (linked in docs)
- 0.5.5 (updated sandbox to latest)

**Comment by promer94** [comment]
In the codesandbox, logout consists of three steps.

* clear the cookie
* clear the user info by ```mutate(null)``` then do revalidation without the cookie
* navigate to home

if you remove cookies from devtool and then focus the window. 
It will revalidate and throw the error. 
But it will not clear the user info.
So we miss the step 2.


For the index page, it would check the user and redirect to dashboard.
For the dashboard page, it would check the error and redirect to index.

Making index page also check the error could solve this problem.
FYI: https://codesandbox.io/s/swr-auth-forked-xdcfm?file=/pages/index.js

**Comment by mikefrancis** [comment]
@promer94 Your sandbox does indeed solve the problem, thanks, so looks to be a problem with the example.

**Comment by JackZheng10** [comment]
I was going through the same bug. This was very helpful! I ended up clearing the cache and then redirecting manually to the login screen, where revalidation would be done for my api/user endpoint. Otherwise, if logging in to another account I had leftover data from the previous account in the cache that had to be revalidated for other endpoints. This was pretty similar to what another user mentioned here: https://github.com/vercel/swr/issues/161#issuecomment-817774756

**Comment by shuding** [comment]
I've updated the example based on @promer94's fix, thank you all!
