### ISSUE TITLE
If a fetcher isn't defined, useSWR shouldn't fetch

### ISSUE THREAD

**Issue by joe-bell** [vercel/swr#1244]
# Bug report

## Description / Observed Behavior

In [Orchest](https://github.com/orchest/orchest), we recently implemented @pacocoursey's fantastic suggestion of [using SWR as a shared state hook](https://paco.sh/blog/shared-hook-state-with-swr).

The pattern works great, but has one caveat: `useSWR` still attempts to fetch the `key` value as an endpoint, even though no `fetcher` is defined.

## Expected Behavior

If a fetcher is `undefined` it should not attempt to fetch

## Repro Steps / Code Example

1. Go to https://codesandbox.io/s/swr-issue-repro-undefined-fetcher-uj8h6?file=/components/layout.jsx
2. Wait for the page to load
3. Open up the `Network` panel in your browser dev tools
4. Click the "Useless Toggle Button" (which toggles a shared `useUseless` state hook)
5. Notice how useSWR is attempting to fetch the `key` of `useless` and returning a 404

## Additional Context

SWR version - `0.5.6`

As a workaround, we're setting `fetcher` to `null`. However, this might trip up potential new users who wish to use the shared state pattern.

---

P.S. Thanks for your continued hard work on this library, it's incredible 🙏

**Comment by pacocoursey** [comment]
I also received an email with confusion about this as a result of my blog post (since I haven't updated it since the default fetcher was added) but in the code, `null` is documented as the correct workaround:

https://github.com/vercel/swr/blob/654fb5e2a3a0f76a1dbc7fcd8562549868c31c31/src/resolve-args.ts#L40-L44

I think we could potentially support it by manually checking `arguments.length` and `typeof arguments[1]` to see whether the user passed `undefined` manually, or it's `undefined` because no argument was passed.

---

I'll also update my blog post based on whatever gets decided here to mention the default fetcher.

**Comment by shuding** [comment]
Thank you Joe and Paco! This will be a breaking change, but I'd love to rollback to the stage that no default fetcher is provided, so let's plan this in 1.x.

**Comment by joe-bell** [comment]
Thank you both!

**Comment by Jeonghyun-Kim** [comment]
This is soooo great 💕💕
