### ISSUE TITLE
better immutability convenience design?

### ISSUE THREAD

**Issue by ianstormtaylor** [vercel/swr#1485]
Why is the new immutable convenience feature modeled as an entirely new hook? Looking at the implementation, it's just sugar for enforcing options:

https://github.com/vercel/swr/blob/c43e6c281ff934fc09438ed94a13ccf56dd24732/immutable/index.ts#L4-L10

But doing it as a new hook means users have to import two separate hooks (in two separate `import` statements because of the different path...). And if users have written any wrappers around the base `useSWR` (eg. like implementing a `useSWRs` for lists) they now need to make two copies if they want to provide the same immutable convenience API downstream.

But further... the current implementation omits `revalidateOnMount`? And it omits enforcing anything for `refresh*` which seems non-obvious—if something is truly immutable wouldn't it not need refreshing?

It seems like it could instead be implemented as an overriding `immutable: true` option? That way any wrappers of `useSWR` would automatically get the convenience just by passing the `options` object that they already do, and fewer imports too. What do you think?

**Comment by shuding** [comment]
Thanks for bringing this up, Ian! I'll share my thoughts behind this implementation for discussion.

<br/>

This helper is also (undocumented) exported as middleware, which can be imported with `import { immutable } from 'swr/immutable'` and then used as `useSWR(key, fetcher, { use: [immutable] })`. This way, all the wrappers around `useSWR` should continue to work with no structural change.

Also worth noting the `swr/infinite` hook also has the middleware exported, and same for all future hooks that we will be working on such as [`swr/subscription`](#1263). IMO this is a more reliable way to extend SWR in the longer term, than adding new options to the hook:

1. We are trying to ensure the orthogonality of all `useSWR` options: options shouldn't have dependency, and changing one option should never affect others.
2. Middleware also imply the order of those different effects and have the ability to override each other, while options don't (still orthogonality).

1 makes it easier to maintain the core so the configuration space won't grow exponentially. If there are N options and each one has 2 states, we only need to consider those 2N cases separately when developing/testing/using this hook. However if one option can have conflicts with another, for example having `immutable: true` and `refreshInterval: 1000`, not only it doesn't make sense, but you will have to test all those 2<sup>N</sup> possibilities. However, middleware move that space into the upper level with better extendibility. 

That's the main reason of adding the `revalidateIfStale` option instead of an `immutable` option, although you have to use it together with configurations such as `revalidateOnFocus: false`.

And for this specific hook, it's more like a sugar but we've been thinking about adding more functionality to it (such as `maxAge`) to make it more powerful.

But after all we need to find a good way to document all this.

<br/>

> But further... the current implementation omits `revalidateOnMount`? And it omits enforcing anything for `refresh*` which seems non-obvious—if something is truly immutable wouldn't it not need refreshing?

`revalidateOnMount` is a switch to force enable/disable data fetching–even if no cache exists, so we're not touching it there. Regarding `refresh*`, indeed they should be disabled by default, and here it shouldn't be simply overriding them. That's my mistake and thank you for noticing!

**Comment by ianstormtaylor** [comment]
Thanks for the thoughtful reply @shuding! That makes total sense then if the immutable sugar is going to be extended to more considerations in the future like `maxAge`, that will be a nice touch. 

And thanks for the `use: [immutable]` approach, I will go with that then.
