### ISSUE TITLE
re-render when using fetcher with useSWR

### ISSUE THREAD

**Issue by oste** [vercel/swr#1695]
## Description / Observed Behavior

When using useSWR with a fetcher the component will re-render even if the data does not change. 

This is an extension of https://github.com/vercel/swr/discussions/1694. The more I research it is looking like there is room for an improvement.

What kind of issues did you encounter with SWR?

## Expected Behavior

Component does not re-render if useSWR data does not change.

## Repro Steps / Code Example

fork the Next.js example here https://swr.vercel.app/examples/ssr

change `const { data, error } = useSWR(API);` to `const { data, error } = useSWR(API, fetcher);`

Notice that `console.log("Is data ready?", !!data);` logs to the console twice instead of once.

## Additional Context

If this is intended, maybe a note can be added to the docs stating that using a fetcher will cause a re-render even if data does not change. This seems to be in contrast to the performance docs on Deep Comparison here https://swr.vercel.app/docs/advanced/performance#deep-comparison

**Comment by icyJoseph** [comment]
Hi,

I check, and while at first thought the first render was caused because of revalidation, but I was unaware of the, I guess relatively new, Deep Comparison function.

`swr` uses dependency tracking, so you only render if you the key you consume changes, for instance, if `isValidating` changes, but you don't `get` it, your component does not render. 

What's happening here, I am afraid, is a problem [stableHash](https://github.com/vercel/swr/blob/ba110c317c4888e577d7143c9c8686cfcea6e218/src/utils/hash.ts#L20).

Using `usePrev` and JSON.stringify, I was checking data

```js
 const { data, error } = useSWR(API, fetcher);

  const prev = usePrev(data);
  console.log(
    "ref eq:",
    data === prev,
    "JSON.stringify:",
    JSON.stringify(data) === JSON.stringify(prev)
  );
```

And while the first two logs are `false false` and then `false true` (meaning the stringified JSONs are equal), the every successive validation (refocusing the tab) yields `true true`. This is why I suspect the `stableHash` is the issue.

Will try to look on it tomorrow, it's very late on my TZ now.

**Comment by icyJoseph** [comment]
I looked a bit more into this, I think the issue was with a re-validate function that ends up calling the state broadcast function, with no data, and that causes a render.

Made  a PR, hopefully someone with more knowledge of the code base can take it further or figure out if there's yet another layer to the issue.

**Comment by oste** [comment]
Thanks a lot for taking a look and for your efforts in fixing the issue.

**Comment by shuding** [comment]
Thank you for looking into this and submitting a PR with test, really appreciate it! I will take a look at the PR and figure out why it would cause a re-render if broadcasting without data (it shouldn't), maybe there is something else wrong.
