### ISSUE TITLE
With React 18 Release, Suspense fallback never called

### ISSUE THREAD

**Issue by pkellner** [vercel/swr#1900]
In this simple example that uses Suspense and a fallback component, the `console.log("Fb")` is never called.

```
import { Suspense } from "react";
import useSWR from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

function Profile() {
  const { data } = useSWR(
    "https://jsonplaceholder.typicode.com/todos/1",
    fetcher,
    { suspense: true }
  );
  return <div>{JSON.stringify(data)}</div>;
}

function Fb() {
  console.log("Fb")
  return <div>Fb loading...</div>
}

function App() {
  return (
    <Suspense fallback={<Fb />}>
      <Profile />
    </Suspense>
  );
}

export default App;
```

package.json

```
{
  "name": "react18suspenseissue",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "post-update": "yarn upgrade --latest"
  },
  "dependencies": {
    "next": "^12.1.4",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "swr": "^1.2.2"
  },
  "description": "Sample Application by Peter Kellner to show Suspense issue"
}

```

**Comment by shuding** [comment]
This isn't an issue, but the default behavior of Next.js with React 18. Next.js does pre-rendering for pages on the server side, including suspense boundaries too. You can see `console.log("Fb")` being executed on the server side.

So when requesting the page, that suspense boundary will be resolved, and the fetched result will be rendered and returned directly in the HTML. And then during hydration, React will not replace the already rendered data with the fallback again. That's why you'll never see it on the client side.

**Comment by pkellner** [comment]
I thought nextjs only pre-renders data when the Async call (useSwr) is in one of the static calls like getserverside props?

**Comment by xld1393679430** [comment]
> 这不是问题，而是 React 18 中 Next.js 的默认行为。Next.js 在服务器端对页面进行预渲染，也包括悬念边界。可以看到`console.log("Fb")`正在服务器端执行。
> 
> 因此，当请求页面时，该悬念边界将被解析，并且获取的结果将被渲染并直接在 HTML 中返回。然后在水化过程中，React 不会再次用后备替换已经渲染的数据。这就是为什么你永远不会在客户端看到它。

只用了react18， 同样的代码 fallback也是不会出现
