### ISSUE TITLE
What's the right way to use useSWRPages with a react-native Flatlist ?

### ISSUE THREAD

**Issue by joris-** [vercel/swr#202]
Hi !
I'm trying to use a react-native Flatlist with useSWRPages but i can't make it works, what's the good implementation ?

Thanks for help :)

**Comment by sergiodxa** [comment]
I had a similar issue recently, because useSWRPages returns components they can not be used with React Native list components without rendering a list per page which make you lose the performance benefits of using those components.

**Comment by sanderfish** [comment]
Running into the same issue while trying to use useSWRPages with react-table as useSWRPages is unable to return the data itself.

**Comment by Jack-Works** [comment]
I'm using `react-window` + `react-window-infinite-loader` + `swr` and here is some buggy behavior. react-window is a virtual list library and react-window-infinite-loader add infinite scroll for it. I use swr for data loading but not working well because react-window-infinite-loader require a `loadMoreItem` that return a Promise but swr doesn't return anything so I have to use `setTimeout` hack to let it work.

The useSWRPages does return a `data`. You need to return an empty `<></>` from the page component in the useSWRPages hook, and add the empty pages into the parent node to let SWR fetch data.

```ts
const { isEmpty, isLoadingMore, isReachingEnd, loadMore, pageCount, pageSWRs, pages } = useSWRPages<
        ProfileIdentifier | null,
        Profile[],
        unknown
    >(
        queryKey,
        ({ offset, withSWR }) => {
            const key: Parameters<typeof fetcher> = [query, offset?.toText()]
            const _ = withSWR(
                // eslint-disable-next-line react-hooks/rules-of-hooks
                useSWR([...key], {
                    suspense: true,
                    fetcher,
                }),
            )
            return React.createElement(React.Fragment)
        },
        (SWR) => { // ...offset
        },
        [queryKey],
    )

    const items = pageSWRs.filter((x) => x).reduce((x, y) => x.concat(y.data), [])
    /// here is the data return by useSWR
    return <>            {pages} // make sure you add the pages even it is empty!
... handling data with virtual list lib
</>
```

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
