### ISSUE TITLE
`cache` not exported globally + `populateCache` not working as expected

### ISSUE THREAD

**Issue by hems** [vercel/swr#2352]
# Bug report

## Description / Observed Behavior

Trying to import `cache` and use it outside of a component yields undefined `cache`?

## Expected Behavior

Be able to access `cache` from anywhere in my application, including outside of components.

## Code Example

````ts
import  { cache } from "swr"

const tags = cache.get('/api/tags/list')
````

## (1) Additional Context

My use case is when using "pure javascript" functions in my application, for instance when coding states using `zustand` i would like to access the global cache and `get` data from there so i can create `optimistData` outside of components and deal with my API / application.

I believe this behaviour was possible on previous SWR version?

## (2) Additional Context

By further investigating the docs i found out the `mutate` function is available globally ( but curiously `cache` isn't? ) and according to [Update Cache After Mutation](https://swr.vercel.app/docs/mutation#update-cache-after-mutation) i should be able to achieve the same results by passing a function to `populateCache`.

## Repro Steps 

````ts
....

async function onSubmit(values, actions) {
  const { label } = values

  const addTag = post("/api/tags/add", { label })

  mutate("/api/tags/list", addTag, {
    populateCache: function (newTag, tags) {
      console.log("new tag ->", newTag)
      console.log("tags ->", tags)
      return [...tags, newTag]
    },
    revalidate: false,
  })

  actions.setSubmitting(false)
}

....

const ListTagsExample = () => {
  const { data: session } = useSession()

  const {
    data: tags,
    error: errorTags,
    isLoading: isLoadingTags,
  } = useSWR("/api/tags/list", fetcher)

  console.log('tags ->', tags)

  return <>{tags.length} fetched</>
}
````

Which does the trick, but for readability/convenience purposes i believe it would be much easier if i could simply do:

````ts

import {cache} from 'swr'
const cachedItems = cache.get('/items/list') || []

try {
  const newItem = await fetchNewItem()
}  catch(error){
 // ... do my error reporting
}

const optimistData = [...cachedItems, newItem]

mutate('/api/items/list', optimisticData, { revalidate: true })

````

OR, more importantly, if my application would have access to the `global default cache object` from SWR without the need to wrap the application on with SWRConfig and implement my own custom "singleton" provider?

## Final Thoughts

Thanks a lot for all the hard work on the library, it's truly incredible and a huge time saver + loads of feature candy, i'm a big fan of your work! 

Unfortunately tough i'm also an old champ who loves to deal with data outside of React Components, which i think is a lot more zen, [zustand](https://github.com/pmndrs/zustand) style :candy: :lollipop:

**Comment by shuding** [comment]
Thanks for opening this! There's a new API for accessing the global cache but we DO NOT recommend using it directly because it might cause issues inside React. If you still want to, the API is `SWRConfig.defaultValue.cache
`.

There're a lot of requests asking for such an API, but we don't recommend people directly accessing the cache because of many reasons. Here are some:

1. It's very easy to go wrong, but SWR makes it safe for you

The snippet you provided is a perfect example:

```js
const cachedItems = cache.get('/items/list') || []

try {
  const newItem = await fetchNewItem()
}  catch(error){
 // ... do my error reporting
}

const optimistData = [...cachedItems, newItem]
```

What if the cache data was updated by another part of the app, **during** `await fetchNewItem()`? Then the optimistic data displayed will be outdated.

That's why SWR has these primitives (rollbackOnError, optimisticData, populateCache) builtin, instead of just giving the cache to you. Under the hood this primitives already considered all the race conditions and other potential issues caused by concurrency.

This is also why, that we wrapped the cache's getter and setter as `mutate(currentValue => newValue)` to make it transactional.

2. React has its own lifecycle

We know that React manages all the UI states, and we want to make sure our data models are mapping correctly to these UI states consistently. 

This is a pretty strong requirement with React's concurrent rendering architecture today. Two instances of the same component can be rendered at the same time (keywords: offscreen components, suspense, transition). If you have a component that reads the cache during rendering, we need to return a snapshot instead of the direct value. This was done inside `useSWR` by us.

There're many other reasons, like exposing such a low level API will extremely limit the possibility of adding new features while maintaining the compatibility.

Hope this explains it well!

**Comment by hems** [comment]
Valid points @shuding, i did have some problems with the current API on SWR 2.0 tough hence why i was trying to sort it out myself by fiddling with the cache. Could you have a look at [this issue for instance](https://github.com/vercel/swr/issues/2355) ?

Also as mentioned [in this other discussion](https://github.com/vercel/swr/discussions/801#discussioncomment-5273242) sometimes updating the cache from a non-react component is necessary and having an API to update / red from SWR outside of components / hooks can be a requirement in some apps.

I didn't know much about what you explained tough, it's really interesting and I'll keep it in mind. Thanks a lot! 🙇
