### ISSUE TITLE
Custom hook doesn't return updated data

### ISSUE THREAD

**Issue by SebastianGaud** [vercel/swr#2360]
# Bug report

## Description / Observed Behavior

When using useSWR inside a custom hook, the data in the component doesn't get updated. If I use the same code directly inside the component it works

## Expected Behavior

I would expect my data to be updated correctly.

## Repro Steps / Code Example

let's take for example this custom hook:

```javascript

export const fetcher = url => axios.get(url).then(res => res.data);

function useZone(zoneId) {
  const {data, isLoading, mutate} = useSWR(`/zone/${zoneId}`, fetcher);
  console.log({data, isLoading})

  return {
    zones: data,
    isLoading: isLoading
  }
}

```

And then we use it inside the component.

```javascript

const SecurityZoneDetail = () => {
  let { zoneId } = useParams();
  const { zone, isLoading } = useZone(zoneId);
  // const { data, isLoading, mutate } = useSWR(`/zone/${zoneId}`, fetcher);

  const [isModalOpen, setIsModalOpen] = useState(false);

  useEffect(() => {
    console.log('[DEBUG] RERENDER', {zone, isLoading})
  }, [zone, isLoading])

  return (
    <PageSpinner isLoading={isLoading}>
      <AddSecurityZoneModal open={isModalOpen}/>
      <SecurityZoneList zones={zone?.childrens} addButton={zone?.is_parent} onClick={() => setIsModalOpen(true)} />
    </PageSpinner>
  );
};

```

the zone inside the component will be always undefined altough the log inside the custom hook show that data is there. 

```console
Object { data: {…}, isLoading: false }
[DEBUG] RERENDER  > Object { zone: undefined, isLoading: true }
```

## Additional Context

SWR version is 2.0.0

I have no idea if I'm missing something here, but I guess it should work like that, an almost equal example is inside the documentation itself: 
https://swr.vercel.app/docs/getting-started#make-it-reusable

**Comment by SebastianGaud** [comment]
Okay uhm.... apparently, a typo, eight hours spent well, Maybe I'll tell my TL to look at this issue to try and understand the importance of typescript.

**Comment by lsdebianchi** [comment]
We are still facing this issue.
Do you have any more insight on how you solved it or on what was the cause of it?

## Our situation
- All our API calls are done through autogenerated SWR custom hook wrappers (so, similar to your example).
- In our local dev setup we have no issues but in production we often face the same issue you described:
_Infinite spinner in the component even if the request was actually successful and the data has been loaded._
- This doesn't happen all the time and it's quite inconsistent.
- If we trigger a re-render of the component, then the loading update to false and the data is available to the component.

## Thoughts
- I feel it's an issue of the returned values of the custom wrapper hook (`{data, isLoading}`) not being passed to the consumer component on update.
- I also feel that this is due to some fetching race condition. Because we experience the bug only in production and not in our local development setup (where our frontend and database are local).


Any extra information could be valuable.

on 
`swr: 2.1.0`
`node: v16.16.0`
`react: 18.2.0`
`react-router-dom: 6.8.0`

**Comment by SebastianGaud** [comment]
Inside this example there was also a typo as you can see on the custom hook I return zones and in the component I used zone as key.

Solved that, the hook still didn't work and I permanently moved the logic inside the component itself, the project is not big and that honestly was just a one time thing; maybe there's some problem in the way I wrote the component or other things in the 
Component tree that prevent SWR to work properly is my guess because I only faced this issue in very specific situations like the one we're both describing. 

Maybe you can try move the hook into another component and see if it works as expected? Altough is difficult to test this stuff in a production environment, probably set up a stage environment with similar specs as production would help. 

Best regards.
