### ISSUE TITLE
Some fetch requests can get stuck when multiple requests are made by a single component

### ISSUE THREAD

**Issue by justhonnoldwegoinghome** [vercel/swr#2446]
# Bug report

## Description / Observed Behavior
When a component makes multiple fetch requests, and once one request gets fulfilled, there is a chance that the remaining requests get stuck (`data` remains as `undefined` despite response being received as seen from network tab).

## Expected Behavior
I would expect the remaining requests to continue getting updated. 

## Repro Steps / Code Example
[Repo to reproduce bug](https://github.com/justhonnoldwegoinghome/swr-stale-error-repro.git)

### ❌ Doesn't work
- `index.tsx` reproduces the error (gets stuck on `Loading...` because `programmingJoke.data` and/or `pun.data` stays as `undefined`) but not all the time. Might require a few browser refreshes for bug to surface. 
```typescript
// index.tsx

import useSWR from "swr";

import { getJoke } from "@/api/getJoke";
import { getProgrammingJoke } from "@/api/getProgrammingJoke";
import { getPun } from "@/api/getPun";

export default function App() {
  const joke = useSWR("joke", getJoke);
  const programmingJoke = useSWR("programming-joke", getProgrammingJoke);
  const pun = useSWR("pun", getPun);

  if (!joke.data || !programmingJoke.data || !pun.data)
    return <div>Loading...</div>;

  return (
    <div>
      <p>{joke.data.joke}</p>
      <br />
      <p>{programmingJoke.data.joke}</p>
      <br />
      <p>{pun.data.joke}</p>
    </div>
  );
}
```
### ✅ Works
- `works.tsx` shows how to resolve error. But doesn't explain observed behaviour. 
```typescript
// works.tsx

import useSWR from "swr";

import { getJoke } from "@/api/getJoke";
import { getProgrammingJoke } from "@/api/getProgrammingJoke";
import { getPun } from "@/api/getPun";

export default function App() {
  const { data: joke } = useSWR("joke", getJoke);
  const { data: programmingJoke } = useSWR(
    "programming-joke",
    getProgrammingJoke
  );
  const { data: pun } = useSWR("pun", getPun);

  if (!joke || !programmingJoke || !pun) return <div>Loading...</div>;

  return (
    <div>
      <p>{joke.joke}</p>
      <br />
      <p>{programmingJoke.joke}</p>
      <br />
      <p>{pun.joke}</p>
    </div>
  );
}
```

## Additional Context

SWR version: 2.0.3

**Comment by promer94** [comment]
Thanks for reporting this ! This is a very good question.

1. SWR have a special mechanism, **it only updates the states that are used by the component**. You can find more detail at [docs](https://swr.vercel.app/docs/advanced/performance#dependency-collection).
2.  `||` is short circuit operator in JavaScript which means if the first condition is true then the rest of **expressions will not be accessed.**

In your example, during first render, since `joke.data` is undefined, **`programmingJoke.data` and `pun.data` would not be used by component.** 


So If api of `programmingJoke` and `pun` resolve faster than `joke`, **then it would not update the states.** `programmingJoke.data` and `pun.data`  would always be `undefined`

You could find a stable reproduce [here](https://codesandbox.io/s/2446-grkt00?file=/src/App.js) 



In your second example, `joke.data` `programmingJoke.data` and `pun.data` are all used by component in first render. So it would always update the state.

**Comment by justhonnoldwegoinghome** [comment]
Thanks for addressing this issue!

I acknowledge points 1 and 2 that you made. However, it doesn't seem to
explain the behaviour. In my first example (without object destructuring), *it
should be akin to using all 4 states* (`data`, `error`, `isLoading`, and
`isValidating`). Since the component uses the hook 3 times, it is as good
as having 12 states. I would expect that whenever 1 of the 12 states
changes, the component will re-render. So the short circuit operator
shouldn't be causing the component to get stuck.

Upon further investigation, I realise that the statement in red is not true
and seems to be the reason for the bug. You can find a reproduction here
<https://codesandbox.io/s/quirky-fast-bbt68e?file=/src/App.js>. If the
statement in red is true, the console.log would be called at least twice in
Block 1. (Do note that I turned strict mode off in the reproduction to
better illustrate my point)

**Comment by MonstraG** [comment]
I think I have another reproduction of the same problem here https://github.com/MonstraG/swr-race-condition-bug
