### ISSUE TITLE
useSWRMutation's trigger response type adds `undefined`

### ISSUE THREAD

**Issue by benevbright** [vercel/swr#2516]
# Bug report

## Description / Observed Behavior

`trigger` response type adds `undefined`

https://github.com/vercel/swr/blob/1389391fa0300b5baa51a9195fb0971b58071318/mutation/types.ts#L76

## Expected Behavior

Since you would use it with `try/catch` (also in the example in the document), it would be better to be `Promise<data>` rather than `Promise<data | undefined>`

SWR version. 
2.1.0

**Comment by rosedo** [comment]
I saw this bug today and now use the typing below.

It fixes the bug and also it seems VS Code and maybe other tools work better with non-default imports.
It's also simpler to have only one typing for one function/hook.

```typescript
import useSWRImport from 'swr'
import {BareFetcher, Key, PublicConfiguration, SWRResponse} from 'swr/_internal'

export const useSWR = <
  R extends object,
  E extends Error,
  C extends Partial<PublicConfiguration<R, E, BareFetcher<R>>> = Partial<PublicConfiguration<R, E, BareFetcher<R>>>
>(
  key: Key,
  fetcher: BareFetcher<R> | null,
  config: C
) => useSWRImport<R, E, C>(key, fetcher, config) as SWRResponse<R | undefined, E, Required<C>>

export const SWR_IMMUTABLE = {revalidateIfStale: false, revalidateOnFocus: false, revalidateOnReconnect: false}
```

Using this, R (response) and E (error) types have to be defined when calling which is probably a good idea.
The config has to be passed but `{}` is accepted.

It's also easier to use SWR_IMMUTABLE as options instead of useSWRImmutable when needed. One reason is that the import is the same. Another is that you can make is conditional: `condition ? SWR_IMMUTABLE : {}`.

Example usage

`const {data, isValidating, error} = useSWR<ApiResponse<KpiData<T>>, AxiosError>(url, getApi<KpiData<T>>, {})`

**Comment by benevbright** [comment]
Thanks @rosedo but the issue is about `useSWRMutation` hook.
