### ISSUE TITLE
Next.js RSC import error: 'swr' does not contain a default export (imported as 'useSWR')

### ISSUE THREAD

**Issue by kusumakan** [vercel/swr#2694]
## Description / Observed Behavior

When import swr in nextjs react server component. It will throw a confusing error `'swr' does not contain a default export (imported as 'useSWR')`

```tsx
import useSWR from "swr";
export default function Home() {
  const { isLoading } = useSWR("/api")
  if (isLoading) {
    return <div>Loading...</div>;
  }
  return <div>Loaded</div>;
}
```

**Comment by azu** [comment]
Reproduce: https://codesandbox.io/p/sandbox/practical-hooks-hcsgzw?file=%2Fapp%2Fpage.tsx%3A9%2C1

The reason is that it was added in [v2.2.0](https://github.com/vercel/swr/releases/tag/v2.2.0) with the `react-server` bundle.

- #2664 

This `react-server` bundle does not has default export. So It show an error message that is difficult to understand.

> error TypeError: (0 , swr__WEBPACK_IMPORTED_MODULE_2__.default) is not a function

This is probably a specification and can be avoided by adding "use client".

```diff
+ "use client";
import useSWR from "swr";
export default function Home() {
  const { isLoading } = useSWR("https://httpstat.us/200");
  if (isLoading) {
    return <div>Loading...</div>;
  }
  return <div>Loaded</div>;
}
```

However, the error messages are confusing and need to be improved.

**Comment by promer94** [comment]
@azu Thanks for your reproduction and explanation. ❤️

> This is probably a intentional and can be avoided by adding ["use client"](https://nextjs.org/docs/getting-started/react-essentials#the-use-client-directive).

* Right. It is intentional. [React actually does the same thing](https://twitter.com/sebmarkbage/status/1673420877491236880?s=20).  

> However, the error messages are confusing and need to be improved.

* I strongly agree with you. The current implementation will throw a early static error which is better than runtime error. But the message itself is confusing for developer who are not familiar with RSC and `react-server`.

**Comment by huozhi** [comment]
Also need to document that in server components, so far only key serialization APIs are available

**Comment by promer94** [comment]
https://swr.vercel.app/docs/with-nextjs#rsc

**Comment by Southclaws** [comment]
Is there a workaround for codegen workflows? I'm [getting this here from Orval](https://github.com/Southclaws/storyden/blob/main/web/src/api/openapi/threads.ts#L8) (issue referenced above) but even though the [component importing this code is "use client"](https://github.com/Southclaws/storyden/blob/a50bde4638bf92f89142ff185440fee934793d5a/web/src/screens/home/Client.tsx#L1) I'm still seeing build failures.

If not, I may just need to fork Orval or do some hacky search+replace or just stop using codegen 🤷

**Comment by uh-sman** [comment]
![Screenshot (59)](https://github.com/vercel/swr/assets/75017192/ad42d766-73f5-45c8-b02a-6fa001a91837)

I have added the "use client" to my swr setup but I am still getting the Error: Attempted to call the default export of C:\Users\USER\Desktop\campusBite\campus-bite\hooks\useCategory.ts from the server but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.

**Comment by Habiba-K** [comment]
./node_modules/@clerk/shared/dist/react/index.mjs
Attempted import error: 'swr' does not contain a default export (imported as 'default2'). how to resolve it

**Comment by mehwish80** [comment]
> ./node_modules/@clerk/shared/dist/react/index.mjs Attempted import error: 'swr' does not contain a default export (imported as 'default2'). how to resolve it


same error I faced
Attempted import error: 'swr' does not contain a default export (imported as 'default2').

**Comment by leilaerhili** [comment]
I don't want to use "use client" are there any other solutions?
