### ISSUE TITLE
In 2.2.4 when I specify response type, key type cannot be inferred automatically

### ISSUE THREAD

**Issue by huksley** [vercel/swr#2821]
# Bug report

## Description / Observed Behavior

Invalid type for key

```typescript
TS7006: Parameter 'key' implicitly has an 'any' type.
    78 | const Page = () => {
  > 79 |   const { data: result } = useSWR<CheckResult>("/api/check", key =>
       |                                                              ^^^
    80 |     fetch(key)
    81 |       .then(response => response.json())
```

## Expected Behavior

How did you expect SWR to behave here?

**key** should have type `string`

## Repro Steps / Code Example

https://codesandbox.io/s/swr-type-issue-tcwxhx?file=/src/App.tsx

See key type error in the code panel.

## Additional Context

SWR version 2.2.4
Typescript 4.9.5

## Workaround

```typescript
  const { data: result } = useSWR("/api/check", key =>
    fetch(key)
      .then(response => response.json() as Promise<CheckResult>)
  );
```

**Comment by promer94** [comment]
This is expected behaviour since typescript does not support partial inference yet.

**Comment by huksley** [comment]
This is not an expected behaviour! We appreciate this library not only because it well designed and works really well, but also for excellent typescript support. Why it was working fine before? Previously it was typed properly

**Comment by promer94** [comment]
Sorry i previously misundestood your problem. SWR behavior indeed changed here. 


But i need to clarify here

```tsx
const { data: result } = useSWR<CheckResult>("/api/check", key => fetcher)
```

if you only provide the first generic here, **the key type actually can't be inferred automatically since day1. It is just explicitly typed as any by SWR** 

The previous behavior was initial added as a workaroud for https://github.com/vercel/swr/issues/1518

But it will cause some other problems like #2758 so we changed it.




> key should have type string.

This is impossible now because of https://github.com/microsoft/TypeScript/issues/26242
