### ISSUE TITLE
How to manipulate the data returned from SWR?

### ISSUE THREAD

**Issue by Ligerx** [vercel/swr#422]
For example, the data from the server comes in the format of `[{ id, count }]` and I'd like to change it to be `{ id: count }`. Is there a 'correct' and efficient pattern for SWR to manipulate the data that comes from the server? I'm also wrapping my SWR calls in custom hooks for re-usability.

**Comment by sergiodxa** [comment]
You can do that in your fetcher function, this is why SWR let you set the fetcher in a per call basis, every usage of useSWR can have a custom made fetcher to do this data formatting.

**Comment by Ligerx** [comment]
The data I'm manipulating isn't that large so this solution should work.
However, if you were thinking about performance, is there any pattern that delays the data formatting until after SWR runs its equality check?

I was considering overriding the `data` in the payload returned by SWR with my own custom value. Maybe wrapping that value in `useMemo` or `useCallback` to be more efficient.

**Comment by sergiodxa** [comment]
I have done both ways, I have a denormalization function I use to format the data I get from my API, and I have used it against the data returned by SWR and in the fetcher itself.

I now tend to do it more in the fetcher, that way the cached data will be formatted how I want it instead of using a different format, this make it easy to mutate the data.

In both cases I haven't had any performance problem.

**Comment by Ligerx** [comment]
perfect thanks for the insight!
