### ISSUE TITLE
Multiple mutations with `mutate`

### ISSUE THREAD

**Issue by augustskare** [vercel/swr#439]
Hey! I'm using `useSWR` to:
1) initially fetch data
2) mutate (using `mutate`) to update data in the UI
3) waiting for the response from the server and `mutate` again with error/success state 

The initial mutate works as expected, but the second one never updates the UI. Any idea on what the issue could be, or something I'm doing worng?

[Codesandbox with an example](https://codesandbox.io/s/brave-ellis-783pd?file=/src/App.js )

**Comment by shuding** [comment]
Thank you for the reproduction! The reason is that you are modifying the original data:

```js
_data[idx] = repo
```

And after `mutate`, SWR compares the new data with the original data (apparently they are the same object), so it skips the re-render.

I changed your example a little bit so the object is cloned and considered different:

```js
const dataCloned = [..._data];
dataCloned[idx] = repo;
const updatedData = await mutate(dataCloned, false);
```

https://codesandbox.io/s/gifted-bash-xfh27?file=/src/App.js:747-783

**Comment by augustskare** [comment]
That solves my issue 🎉 Thanks for the fast reply and pointing me in the right direction! 😄
