### ISSUE TITLE
useSWRInfinite leaks { originalData: undefined, force: false } objects from cache when setSize is called with null first page key

### ISSUE THREAD

**Issue by eddiew** [vercel/swr#774]
# Bug report

## Description / Observed Behavior

useSWRInfinite returns data as { originalData: undefined, force: false } when setSize is called with null first page key. 

## Expected Behavior

data is undefined when first key is null, regardless of calls to setSize

## Repro Steps / Code Example

WIth null first page key, call setSize.

## Additional Context

SWR version 0.3.8

We have page keys that depend on other data to load, so the first page key is while the component mounts and fetches data for the first time. Meanwhile, we call setSize based on another variable that is immediately available. Delaying our calls to setSize
until the page keys are non-null resolves this issue, but leaking the cache objects is a bug that can be resolved anyway.

**Comment by derindutz** [comment]
I think I found the bug. If `firstPageKey` is null [here](https://github.com/vercel/swr/blob/52a06bc8ba980e03d03b5d2366b5551bcf44c41e/src/use-swr-infinite.ts#L97), contextCacheKey stays as null. Then on [this line](https://github.com/vercel/swr/blob/52a06bc8ba980e03d03b5d2366b5551bcf44c41e/src/use-swr-infinite.ts#L194), the cache gets set with key null – serialized to `''` – and value `{ force: true}` or `{ originalData, force: false }` on the line above. Now any time a key serializes to `''` on any SWR call, the junk value comes back as data.

This issue is related: https://github.com/vercel/swr/issues/637

**Comment by payalord** [comment]
Any progress on fixing this or not yet? Thanks. Looks like for now then there is have to be done additional data structure validation then, to avoid unpredictable problems.

**Comment by payalord** [comment]
Same problem happened with useSWR too, when `null` passed as key, sometimes it returns `{ originalData: undefined, force: false }`. In our case it happened when we correctly switched to the right page from another in react app.

**Comment by payalord** [comment]
Is it possible that since if both `useSWRInfinite` and `useSWR` used at the same time in the project. Then they can interfere together for the `null` cached key? For example `useSWRInfinite` saved data with structure `{ originalData: undefined, force: false }` for some data where there was no key, so with `null` key. Later on `useSWR` tried to get the data from the cache with `null` key and returned `{ originalData: undefined, force: false }` that previously `useSWRInfinite` saved there?

**Comment by payalord** [comment]
`originalData` is renamed with latest updates to just `data`. So now, I have updated my previous comments. So junk data will be now `{ data: undefined, force: false }`. I have checked source code. This problem might be happening with `useSWR` function,  because both functions `useSWR` and `useSWRInfinite` using same shared `cache`. Which is wrong, because real world complex projects can use both of this functions. So when `useSWRInfinite` will run it will store `{ data: undefined, force: false }` in `cache` under `null` key then later `useSWR` can read it by the same `null` key. But for `useSWR` we expect in `data` to be returned the data (`undefined` value in this particular case). While in data `useSWR` returns `{ data: undefined, force: false }`.

**Comment by payalord** [comment]
So the solution or for both functions is to have one structure of `data` to store in this one shared `cache`. So both functions can read it and return the right appropriate values. Or use separated `cache`.

**Comment by payalord** [comment]
Maybe even better to create a `type` for data to be stored in `cache`. So you can't store in the `cache` any kind of data structure. Let say `cache` will accept always this only `{ data<any>, force<boolean> }`. Something like that. And `useSWR` function need to be updated then too.
