### ISSUE TITLE
Data not resetting after shallow routing

### ISSUE THREAD

**Issue by Swearengen** [vercel/swr#803]
# Bug report

## Description / Observed Behavior

I am using next.js and have few links with shallow routing. On the first page, I am using SWRInfinite and with load more button I can load next pages.

In case I click on some other page in my app or do the shallow routing and go back to my initial page with SWRInfinite I see that previously loaded results are still present (the results I get after clicking the load more button). 

## Expected Behavior

I would expect that SWR clears the cache after unmounting component

this is possible solution:

`useEffect(() => {
    return () => {
      cache.clear()
    }
  }, []);`

## Repro Steps / Code Example

1. Go to infinite load page
2. Try loading more 
3. navigate to idex page
4. click to infinite load page again

[CodeSandbox](https://codesandbox.io/s/with-persist-page-qo5de)

## Additional Context

SWR version - 0.3.6

**Comment by koba04** [comment]
The cache of SWR is not per component, which is a global cache. I think this is intended behavior because it makes sense in many cases.
For example, let's think about a case navigating from a timeline page to a detailed page, and then going back to the timeline page. We would expect the timeline page is restored when we go back from the detail page to the timeline page.

But it might make sense that `useSWRInfinite` has an option to clear the `size` value.

**Comment by isBatak** [comment]
@koba04 it depends if the user goes back by clicking on the browser back button or he clicks on the main navigation link.
Can we somehow detect the browser back and keep the size and in any other case rest the size?

**Comment by shuding** [comment]
Indeed like what @koba04 said this isn’t a bug. It’s a feature to recover the scroll position for infinite scrolling scenarios.

I can’t think of a case that you don’t want to recover the scroll position when you hit the Back button (for example Twitter or Facebook). And when you hit the link on the navigation bar (in this case the browser won’t reset the scroll position), it’s good to show all the previous loaded pages too. Why do you want to not reuse the cache?
