### ISSUE TITLE
useSWRInfinite does not restore scroll position

### ISSUE THREAD

**Issue by Qrymy** [vercel/swr#857]
# Bug report

## Description / Observed Behavior

I'm using `useSWRInfinite` with `firestore`, however it does not restore scroll position after browser back.
This is current behavior.

https://user-images.githubusercontent.com/26219456/103517383-5c542e80-4eb5-11eb-9344-6a42f7775730.mov

## Expected Behavior

After browser back, it should be kept scroll position before url changed.

## Repro Steps / Code Example

[This](https://firebase-swr.vercel.app/) is example project, and [this](https://github.com/Qrymy/firebase-swr) is the repository.

## Additional Context

SWR version: 0.3.11

**Comment by huozhi** [comment]
caching browser scroll position is out of of swr's scope. you can memorize the scroll position in local/session storage, read and scroll to the position when navigation happens.

**Comment by Qrymy** [comment]
@huozhi 
Thanks for your response!
I know an idea that using local/session storage, but I've found "Pagination and scroll position recovery" statement at [top page](https://swr.vercel.app/), I've made this issue.

If you know, please let me know this statement's meaning.

Thanks

**Comment by huozhi** [comment]
@Qrymy are you using safari browser? I tried the example link in the description with both chrome and safari, it turns out when you navigate back chrome will preserve the scroll position, but on safari it doesn't maintain the scroll position in last page. 

seems this is not a stable cross browser behavior? 🤔 cc @shuding if you have any insights about this or any other elegant solution about this.

**Comment by Qrymy** [comment]
@huozhi 
I'm using Chrome with Mac, but it doesn't keep scroll position...
I would like to know scroll position recovery is achieved with only SWR?

**Comment by huozhi** [comment]
by default browser API `history.scrollRestoration` is `'auto'` indicating it will restore the scroll position on this page.
reference: https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration

so you should be able to achive it even without SWR. SWR infinite API is trying to cache the data of your list to let the list render smoothly instead of shaking.

UPDATE: I tried your link on safari and chrome a few more times, sometimes it restore the position correctly but sometimes not. usually failed on the first time then it works well.

**Comment by Qrymy** [comment]
@huozhi 
Thanks, I'll try to check `scrollRestoration` settings!

**Comment by grazianodev** [comment]
I'm having the same issue... Can anyone on the team please confirm whether scroll position recovery should be expected with useSWRInfinite (as the documentation seems to suggest), or if it's something we have to take care of? 

I'm using useSWRInfinite with Next.js by the way, so when I hit the back button I'm doing a client-side transition.

**Comment by huozhi** [comment]
@grazianodev 
* restoring scrolling position between navigations is a browser native feature
* useSWRInfinite is responsible for providing cahced state between navigations

I'm not sure the case you're working with next.js, it would be great if you can provide any minimal reproduction. if it's a next.js issue we can also work with next.js team to solve it out.

**Comment by grazianodev** [comment]
Thank you @huozhi. I'll try to create a minimal reproduction as you suggest. 

In the meanwhile, I might be wrong but as far as I know native scrolling positions only work between different pages, and not when routing is done client-side in single page applications (like Next.js). 

Also, just to be clear data caching is working for me, meaning when I hit the back button useSWRInfinite correctly shows the cached data that I had already fetched. The page however has scrolled to the top when I go back.

**Comment by grazianodev** [comment]
Hey @huozhi, I've done some tests and I think I've found the issue. It's very easy to reproduce, but I've put together a quick example anyway: [https://github.com/grazianodev/useswrinfinite-scroll](https://github.com/grazianodev/useswrinfinite-scroll) 

The problem arises with pages generated statically by Next.js (using getStaticProps). If you don't use getStaticProps, scroll restoration works flawlessly; if you use it, it gets weird because scroll restoration of page A seems to work based on how much content is in page B: if there's little content in page B, when you go back to page A it has scrolled back to top, regardless of how much you scrolled before going to page B (i.e. doesn't work); if there's a lot of content in page B, when you go back to page A scroll restoration works, but as you will see the scroll is restored when you're still in page B, causing it to do an ugly jump. 

In any case, I'm pretty sure it has to do with the fact that for static pages Next.js requests a "pagename.json" file in the background to render the page, and the time it takes to fetch it creates jumps and inconsistencies in the scroll positions... 

Does this sound like something that can be worked on?

**Comment by huozhi** [comment]
@grazianodev thanks for providing the reproduction. sounds like it's because next.js SSG will unmount the DOM nodes of whole page while navigating, so that the default scroll position cannot be preserved?

IMO I feel it's more like a next.js behavior which could still be optimized to improve the experience in long term for scroll position restoration. it's not an issue for SWR so I'd like to keep this issue as closed.

I think you can try to memoize the scrolling position by router path as workaround. labeled this issue with "help wanted" to see if anyone have better solutions for this.
