### ISSUE TITLE
mutate is not rerendering

### ISSUE THREAD

**Issue by EliasSchlatter** [vercel/swr#858]
# Bug report

## Description / Observed Behavior

I'm using mutate() to update data. Here is a little snip of what I want to do:

```
export const updateList = async (body, mutate) => {
  const res = await mutate(sendPutRequest(body), false);
  return res;
};
```

I think mutate is working and data is properly updated, because if the UI is updated for another reason (for example a scroll event) the fresh data appears. But for some reason the UI is not updated, right after executing mutate()

## Expected Behavior

I would expect that as soon as mutate is, done all UI, that refers to the updated data, is refreshed.

## Repro Steps / Code Example

Here is a [CodeSandbox](https://codesandbox.io/s/billowing-field-s8d11?file=/pages/index.js) 

## Additional Context

usually swr acts expected. The issue appears only if I try to refer a value out of an array. So if the response is:
```
{
   _id: 123,
   active: true
}
```
and I'm trying to update some UI elements in terms of active, it **will** work.

But if the response is:
```
[{
   _id: 123,
   active: true
},
{
   _id: 456,
   active: false
}]
```
and I'm trying to update some UI elements in terms of active, it **won't** work.

also there is another ticket #662 wich is very similar to this and where i postet the CodeSandbox, but it was closed at that time allready and I'm not sure if someone will have a look on it anymore. Sorry for the duplication and if there would be a better flow than creating a new ticket to get attention on a closed topic, please let me know.

SWR version: 0.3.11

**Comment by promer94** [comment]
In codesanbox, i think the problem is 

```js
const fakePutRequest = (body) => {
  setTimeout(() => {
    return body;
  }, 300);
};
```
fakePutRequest will return ```undefined```

```mutate(undefined, false)``` will not make component rerender.

**Comment by EliasSchlatter** [comment]
Hi @promer94,

thanks for your response. I don't think that's the problem, because if you take a look at the console tab while clicking the star button, you'll see that the array "exerciseIds" is set and also changes its value.

**Comment by EliasSchlatter** [comment]
Hey, I just saw that the console log for some reason is not visible from other accounts. Here is a picuture of mine:

![swr](https://user-images.githubusercontent.com/13678087/103561940-9542d200-4eba-11eb-8b6c-4bfc1f412726.JPG)

the same value that is logged will be returned from fakePutRequest.

**Comment by promer94** [comment]
https://codesandbox.io/s/fancy-smoke-k1016?file=/pages/index.js

**Comment by EliasSchlatter** [comment]
Hi @promer94 ,

sorry for the stupid mistake. I updated my original [CodeSandbox](https://codesandbox.io/s/billowing-field-s8d11?file=/pages/index.js), but the issue remains. Hopefully you can help me and thanks for your efforts so far.

**Comment by Munnopsis** [comment]
Hi together, 

I ran into pretty the same issue.

In my case i call mutate([newData], false), with [newData] coming as response from my backend and my UI does not refresh.

Also when I deepclone the returned newData before I call mutate([...newData], false), it does not refresh.

When I deepclone an {...object} with spread syntax **before** it is sent to the backend, then replace the object in [...data] with the response (updated Object) resulting in [newData] and afterwards calling mutate([newData], false) the refresh works fine. But without the spread syntax before the update request it does not work.

But when I deepclone the returned newData before I call mutate([...newData], false), it does not refresh.

With mutate(newData,true) it always refreshes, but I don't want so send an additional request because the newData is already there.

This behavior is a mystery for me, since objects coming from a server are as far as I know always a new reference.

Does anyone have an idea what causes this behavior and how to fix it ?

Im sorry but i could not reproduce this issue in sandbox.

My Database is running on Mongo.

**Comment by shuding** [comment]
First of all, thanks for opening this issue! But please simplify your reproduction to keep it **minimal**. There're a lot of unrelated stuff such as `isNoted`, and that will not help the maintainers understanding the problem you're having. 

@Munnopsis can you try to reproduce it by adding some mock up to this CodeSandbox template: https://codesandbox.io/s/swr-basic-wnqi2? It has nothing to do with your database, you can use a fake fetcher.

**Comment by EliasSchlatter** [comment]
@shuding @promer94 hey guys, I updated the [CodeSandbox](https://codesandbox.io/s/billowing-field-s8d11?file=/pages/api.js).

**Comment by promer94** [comment]
You should not mutate the original data from SWR. 

```js
 let newList = [...list.data];
 // doing this will affect the original list.data which is stored in cache
 newList[buttonIndex].active = !newList[buttonIndex].active;
```
Instead, you should use [immer](https://github.com/immerjs/immer) to make safe mutations

```js
 let newList = produce(list.data, (data) => {
      data[buttonIndex].active = !data[buttonIndex].active;
});
```

FYI
https://codesandbox.io/s/focused-allen-msrz6?file=/pages/index.js:1086-1199
