### ISSUE TITLE
Wrong cache result returned for same key but different fetch function

### ISSUE THREAD

**Issue by Janpot** [vercel/swr#873]
# Bug report

## Description / Observed Behavior

Using different fetch functions but with overlapping keys makes the cache confused.

## Expected Behavior

Each fetch function I provide should have its own isolated cache. i.e. the function should be part of the cache key, as if you would do (see repro steps)
```js
function applyFn(fn, ...args) {
  return fn(...args)
}

useSWR([fetchHello, 'swr'], applyFn)
useSWR([fetchGoodbye, 'swr'], applyFn)
```

## Repro Steps / Code Example

```js
import useSWR from "swr";

function fetchHello(name) {
  return `hello ${name}`;
}

function fetchGoodbye(name) {
  return `goodbye ${name}`;
}

export default function IndexPage() {
  const { data: hello } = useSWR("swr", fetchHello);
  const { data: goodbye } = useSWR("swr", fetchGoodbye);

  return (
    <div>
      hello: {hello}
      <br />
      goodbye: {goodbye}
    </div>
  );
}
```

https://codesandbox.io/s/swr-issue-overlapping-cache-9xuqs

Notice how it displays 
>hello: hello swr
>goodbye: hello swr

instead of

>hello: hello swr
>goodbye: goodbye swr

## Additional Context

SWR version. 
0.4.0

**Comment by shuding** [comment]
This is expected behavior because the resource is always identified by the key. Like React hooks `useCallback(fn, [key])` won’t return the new result when `fn` changes (also technically it’s not possible to make fetcher part of the key, e.g., people use anonymous inline functions as the fetcher).

What you described:

```js
useSWR([fetchHello, 'swr'], applyFn)
```

actually looks great because the fetch method also identifies the resource in your case, so it’s in the key and that works.

And you can always create your custom hooks to simply the application logic (SWR works the best at the resource level):

```js
// libs/resource.js
const createUseResource = 
  fetcher => key => useSWR([fetcher, key], applyFn)
const useHello = createUseResource(fetchHello)

// components/foo.js
useHello('swr')
```
